version: "3.8"
services:
  frontend:
    image: lmaslovs/myportfolio.frontend:latest
    networks:
      - my-network

  backend:
    image: lmaslovs/myportfolio.backend:latest
    environment:
      MONGODB_URI: ${MONGODB_URI}
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "81:80" # Internal port mapped to 81 for HTTP
      - "444:443" # Internal port mapped to 444 for HTTPS
    environment:
      - SERVER_NAME=${SERVER_NAME}
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
