# .github/workflows/deploy.yml (in your deployment repo)
name: Deploy

on:
  repository_dispatch:
    types: [trigger-deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine changed repository
        id: changed_repo
        run: echo "::set-output name=repo::${{ github.event.client_payload.repo }}"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd ~/my-portfolio.deployment
            git pull origin main
            sudo docker-compose pull
            sudo docker-compose up -d --no-deps $(echo ${{ steps.changed_repo.outputs.repo }} | cut -d'/' -f2)
